# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercises.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1931, 982))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1001, 1091))
        self.widget_2.setMinimumSize(QtCore.QSize(55, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setItalic(True)
        self.widget_2.setFont(font)
        self.widget_2.setAutoFillBackground(False)
        self.widget_2.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 116, 91, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widget_2.setObjectName("widget_2")
        self.q1 = QtWidgets.QLabel(self.widget_2)
        self.q1.setGeometry(QtCore.QRect(230, 180, 451, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q1.setFont(font)
        self.q1.setMouseTracking(False)
        self.q1.setTabletTracking(False)
        self.q1.setAcceptDrops(False)
        self.q1.setAutoFillBackground(False)
        self.q1.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q1.setScaledContents(False)
        self.q1.setObjectName("q1")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(60, 200, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.ans11_1 = QtWidgets.QComboBox(self.widget_2)
        self.ans11_1.setGeometry(QtCore.QRect(320, 310, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_1.setFont(font)
        self.ans11_1.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_1.setObjectName("ans11_1")
        self.ans11_1.addItem("")
        self.ans11_1.addItem("")
        self.ans11_1.addItem("")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(60, 450, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.q2 = QtWidgets.QLabel(self.widget_2)
        self.q2.setGeometry(QtCore.QRect(180, 430, 551, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q2.setFont(font)
        self.q2.setMouseTracking(False)
        self.q2.setTabletTracking(False)
        self.q2.setAcceptDrops(False)
        self.q2.setAutoFillBackground(False)
        self.q2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q2.setScaledContents(False)
        self.q2.setObjectName("q2")
        self.ans11_2 = QtWidgets.QComboBox(self.widget_2)
        self.ans11_2.setGeometry(QtCore.QRect(330, 550, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_2.setFont(font)
        self.ans11_2.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_2.setObjectName("ans11_2")
        self.ans11_2.addItem("")
        self.ans11_2.addItem("")
        self.ans11_2.addItem("")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(60, 730, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.check11_1 = QtWidgets.QPushButton(self.widget_2)
        self.check11_1.setGeometry(QtCore.QRect(510, 310, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check11_1.setFont(font)
        self.check11_1.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check11_1.setObjectName("check11_1")
        self.check11_2 = QtWidgets.QPushButton(self.widget_2)
        self.check11_2.setGeometry(QtCore.QRect(520, 550, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check11_2.setFont(font)
        self.check11_2.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check11_2.setObjectName("check11_2")
        self.q2_2 = QtWidgets.QLabel(self.widget_2)
        self.q2_2.setGeometry(QtCore.QRect(160, 700, 581, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q2_2.setFont(font)
        self.q2_2.setMouseTracking(False)
        self.q2_2.setTabletTracking(False)
        self.q2_2.setAcceptDrops(False)
        self.q2_2.setAutoFillBackground(False)
        self.q2_2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q2_2.setScaledContents(False)
        self.q2_2.setObjectName("q2_2")
        self.ans11_3 = QtWidgets.QComboBox(self.widget_2)
        self.ans11_3.setGeometry(QtCore.QRect(340, 830, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_3.setFont(font)
        self.ans11_3.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_3.setObjectName("ans11_3")
        self.ans11_3.addItem("")
        self.ans11_3.addItem("")
        self.ans11_3.addItem("")
        self.check11_3 = QtWidgets.QPushButton(self.widget_2)
        self.check11_3.setGeometry(QtCore.QRect(530, 840, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check11_3.setFont(font)
        self.check11_3.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check11_3.setObjectName("check11_3")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(250, 30, 451, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius: 20px;\n"
"border: 2px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.back_gr11 = QtWidgets.QPushButton(self.widget_2)
        self.back_gr11.setGeometry(QtCore.QRect(20, 900, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.back_gr11.setFont(font)
        self.back_gr11.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.back_gr11.setObjectName("back_gr11")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(930, 0, 1001, 1111))
        self.widget_3.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 116, 91, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widget_3.setObjectName("widget_3")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(60, 150, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.q1_2 = QtWidgets.QLabel(self.widget_3)
        self.q1_2.setGeometry(QtCore.QRect(150, 130, 711, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.q1_2.setFont(font)
        self.q1_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.q1_2.setMouseTracking(True)
        self.q1_2.setTabletTracking(False)
        self.q1_2.setAcceptDrops(False)
        self.q1_2.setAutoFillBackground(False)
        self.q1_2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q1_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.q1_2.setScaledContents(False)
        self.q1_2.setWordWrap(True)
        self.q1_2.setObjectName("q1_2")
        self.ans11_4_1 = QtWidgets.QComboBox(self.widget_3)
        self.ans11_4_1.setGeometry(QtCore.QRect(310, 260, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_4_1.setFont(font)
        self.ans11_4_1.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_4_1.setObjectName("ans11_4_1")
        self.ans11_4_1.addItem("")
        self.ans11_4_1.addItem("")
        self.ans11_4_1.addItem("")
        self.ans11_4_2 = QtWidgets.QComboBox(self.widget_3)
        self.ans11_4_2.setGeometry(QtCore.QRect(490, 260, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_4_2.setFont(font)
        self.ans11_4_2.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_4_2.setObjectName("ans11_4_2")
        self.ans11_4_2.addItem("")
        self.ans11_4_2.addItem("")
        self.ans11_4_2.addItem("")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(60, 430, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.check11_4 = QtWidgets.QPushButton(self.widget_3)
        self.check11_4.setGeometry(QtCore.QRect(660, 260, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check11_4.setFont(font)
        self.check11_4.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check11_4.setObjectName("check11_4")
        self.q1_3 = QtWidgets.QLabel(self.widget_3)
        self.q1_3.setGeometry(QtCore.QRect(180, 400, 581, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.q1_3.setFont(font)
        self.q1_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.q1_3.setMouseTracking(True)
        self.q1_3.setTabletTracking(False)
        self.q1_3.setAcceptDrops(False)
        self.q1_3.setAutoFillBackground(False)
        self.q1_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q1_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.q1_3.setScaledContents(False)
        self.q1_3.setWordWrap(True)
        self.q1_3.setIndent(10)
        self.q1_3.setOpenExternalLinks(False)
        self.q1_3.setObjectName("q1_3")
        self.ans11_5_1 = QtWidgets.QComboBox(self.widget_3)
        self.ans11_5_1.setGeometry(QtCore.QRect(220, 540, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_5_1.setFont(font)
        self.ans11_5_1.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_5_1.setObjectName("ans11_5_1")
        self.ans11_5_1.addItem("")
        self.ans11_5_1.addItem("")
        self.ans11_5_1.addItem("")
        self.check11_5 = QtWidgets.QPushButton(self.widget_3)
        self.check11_5.setGeometry(QtCore.QRect(590, 540, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check11_5.setFont(font)
        self.check11_5.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check11_5.setObjectName("check11_5")
        self.ans11_5_2 = QtWidgets.QComboBox(self.widget_3)
        self.ans11_5_2.setGeometry(QtCore.QRect(400, 540, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_5_2.setFont(font)
        self.ans11_5_2.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_5_2.setObjectName("ans11_5_2")
        self.ans11_5_2.addItem("")
        self.ans11_5_2.addItem("")
        self.ans11_5_2.addItem("")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(60, 700, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.q2_3 = QtWidgets.QLabel(self.widget_3)
        self.q2_3.setGeometry(QtCore.QRect(150, 690, 711, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q2_3.setFont(font)
        self.q2_3.setMouseTracking(False)
        self.q2_3.setTabletTracking(False)
        self.q2_3.setAcceptDrops(False)
        self.q2_3.setAutoFillBackground(False)
        self.q2_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q2_3.setScaledContents(False)
        self.q2_3.setWordWrap(True)
        self.q2_3.setObjectName("q2_3")
        self.ans11_6 = QtWidgets.QComboBox(self.widget_3)
        self.ans11_6.setGeometry(QtCore.QRect(340, 800, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_6.setFont(font)
        self.ans11_6.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_6.setObjectName("ans11_6")
        self.ans11_6.addItem("")
        self.ans11_6.addItem("")
        self.ans11_6.addItem("")
        self.check11_6 = QtWidgets.QPushButton(self.widget_3)
        self.check11_6.setGeometry(QtCore.QRect(540, 800, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check11_6.setFont(font)
        self.check11_6.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check11_6.setObjectName("check11_6")
        self.nextp2_11 = QtWidgets.QPushButton(self.widget_3)
        self.nextp2_11.setGeometry(QtCore.QRect(760, 900, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nextp2_11.setFont(font)
        self.nextp2_11.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.nextp2_11.setObjectName("nextp2_11")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(410, 20, 71, 70))
        self.label_9.setMinimumSize(QtCore.QSize(55, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border-radius:35px;\n"
"color: rgb(0, 170, 255);\n"
"background-color: rgb(255, 196, 202);\n"
"border: 2px solid white;\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setGeometry(QtCore.QRect(660, 20, 71, 70))
        self.label_11.setMinimumSize(QtCore.QSize(55, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border-radius:35px;\n"
"color: rgb(255, 85, 255);\n"
"background-color: rgb(255, 196, 202);\n"
"border: 2px solid white;\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(280, 20, 71, 70))
        self.label_2.setMinimumSize(QtCore.QSize(55, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius:35px;\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 196, 202);\n"
"border: 2px solid white;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setGeometry(QtCore.QRect(530, 20, 71, 70))
        self.label_10.setMinimumSize(QtCore.QSize(55, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border-radius:35px;\n"
"color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 196, 202);\n"
"border: 2px solid white;\n"
"")
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.check11_1.clicked.connect(self.check_answer11_1)
        self.check11_2.clicked.connect(self.check_answer11_2)
        self.check11_3.clicked.connect(self.check_answer11_3)
        self.check11_4.clicked.connect(self.check_answer11_4)
        self.check11_5.clicked.connect(self.check_answer11_5)
        self.check11_6.clicked.connect(self.check_answer11_6)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.q1.setText(_translate("MainWindow", "えいご __(1)__ できます。"))
        self.label_3.setText(_translate("MainWindow", "1"))
        self.ans11_1.setItemText(0, _translate("MainWindow", "1?"))
        self.ans11_1.setItemText(1, _translate("MainWindow", "が"))
        self.ans11_1.setItemText(2, _translate("MainWindow", "を"))
        self.label_4.setText(_translate("MainWindow", "2"))
        self.q2.setText(_translate("MainWindow", "イギリス __(2)__ べんきょうします。"))
        self.ans11_2.setItemText(0, _translate("MainWindow", "2?"))
        self.ans11_2.setItemText(1, _translate("MainWindow", "で"))
        self.ans11_2.setItemText(2, _translate("MainWindow", "に"))
        self.label_5.setText(_translate("MainWindow", "3"))
        self.check11_1.setText(_translate("MainWindow", "Check"))
        self.check11_2.setText(_translate("MainWindow", "Check"))
        self.q2_2.setText(_translate("MainWindow", "あの　みせ ___(3)___ 食べましょう。"))
        self.ans11_3.setItemText(0, _translate("MainWindow", "3?"))
        self.ans11_3.setItemText(1, _translate("MainWindow", "で"))
        self.ans11_3.setItemText(2, _translate("MainWindow", "に"))
        self.check11_3.setText(_translate("MainWindow", "Check"))
        self.label.setText(_translate("MainWindow", "Question 1. Choose the correct word:"))
        self.back_gr11.setText(_translate("MainWindow", "Back"))
        self.label_6.setText(_translate("MainWindow", "4"))
        self.q1_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Noto Sans JP\',\'ヒラギノ角ゴ Pro W3\',\'Hiragino Kaku Gothic Pro\',\'メイリオ\',\'Meiryo\',\'ＭＳ Ｐゴシック\',\'sans-serif\'; font-size:20px; color:#717171; background-color:#fffdf7;\">テーブルの うえ           バナナ</span><span style=\" font-family:\'Noto Sans JP\',\'ヒラギノ角ゴ Pro W3\',\'Hiragino Kaku Gothic Pro\',\'メイリオ\',\'Meiryo\',\'ＭＳ Ｐゴシック\',\'sans-serif\'; font-size:20px; font-weight:400; color:#717171; background-color:#fffdf7;\"/><span style=\" font-family:\'Noto Sans JP\',\'ヒラギノ角ゴ Pro W3\',\'Hiragino Kaku Gothic Pro\',\'メイリオ\',\'Meiryo\',\'ＭＳ Ｐゴシック\',\'sans-serif\'; font-size:20px; color:#717171; background-color:#fffdf7;\">あります。</span></p><p><br/><span style=\" font-family:\'Noto Sans JP\'; font-size:18px; color:#717171;\"/><span style=\" font-family:\'Noto Sans JP\'; font-size:18px; font-weight:400; color:#717171;\"/><a name=\"ui-id-4-button\"/><a href=\"https://a1.marugotoweb.jp/en/grammar_topic6_11.php#nogo\"><span style=\" font-family:\'Verdana\',\'Arial\',\'sans-serif\'; font-size:20px; font-weight:400; color:#666666; background-color:#fffdf7; vertical-align:middle;\"><br/></span></a><span style=\" font-family:\'Noto Sans JP\'; font-size:18px; font-weight:400; color:#717171;\"/><a name=\"ui-id-4-button\"/><a href=\"https://a1.marugotoweb.jp/en/grammar_topic6_11.php#nogo\"><span style=\" font-family:\'Verdana\',\'Arial\',\'sans-serif\'; font-size:20px; font-weight:400; color:#666666; background-color:#fffdf7; vertical-align:middle;\"><br/></span></a></p></body></html>"))
        self.q1_2.setText(_translate("MainWindow", "テーブルの　うえ __(4)__  バナナ __(5)__ あります。"))
        self.ans11_4_1.setItemText(0, _translate("MainWindow", "4?"))
        self.ans11_4_1.setItemText(1, _translate("MainWindow", "で"))
        self.ans11_4_1.setItemText(2, _translate("MainWindow", "に"))
        self.ans11_4_2.setItemText(0, _translate("MainWindow", "5?"))
        self.ans11_4_2.setItemText(1, _translate("MainWindow", "が"))
        self.ans11_4_2.setItemText(2, _translate("MainWindow", "を"))
        self.label_7.setText(_translate("MainWindow", "5"))
        self.check11_4.setText(_translate("MainWindow", "Check"))
        self.q1_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.q1_3.setText(_translate("MainWindow", "A:__(6)__  サッカーを　しますか。                 B: いいえ、__(7)__  しません。"))
        self.ans11_5_1.setItemText(0, _translate("MainWindow", "6?"))
        self.ans11_5_1.setItemText(1, _translate("MainWindow", "よく"))
        self.ans11_5_1.setItemText(2, _translate("MainWindow", "ぜんぜん"))
        self.check11_5.setText(_translate("MainWindow", "Check"))
        self.ans11_5_2.setItemText(0, _translate("MainWindow", "7?"))
        self.ans11_5_2.setItemText(1, _translate("MainWindow", "よく"))
        self.ans11_5_2.setItemText(2, _translate("MainWindow", "あまり"))
        self.label_8.setText(_translate("MainWindow", "6"))
        self.q2_3.setText(_translate("MainWindow", "やすみの　ひに  __(8)__  かいものを　します。"))
        self.ans11_6.setItemText(0, _translate("MainWindow", "8?"))
        self.ans11_6.setItemText(1, _translate("MainWindow", "ときどき"))
        self.ans11_6.setItemText(2, _translate("MainWindow", "あまり"))
        self.check11_6.setText(_translate("MainWindow", "Check"))
        self.nextp2_11.setText(_translate("MainWindow", "Next"))
        self.label_9.setText(_translate("MainWindow", "く"))
        self.label_11.setText(_translate("MainWindow", "く"))
        self.label_2.setText(_translate("MainWindow", "ど"))
        self.label_10.setText(_translate("MainWindow", "が"))

    def check_answer11_1(self):
        selected_answer11_1 = self.ans11_1.currentText()
        if selected_answer11_1 == 'が':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()
    def check_answer11_2(self):
        selected_answer11_2 = self.ans11_2.currentText()
        if selected_answer11_2 == 'で':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()

    def check_answer11_3(self):
        selected_answer11_3 = self.ans11_3.currentText()
        if selected_answer11_3 == 'で':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()
    def check_answer11_4(self):
        selected_answer11_4_1 = self.ans11_4_1.currentText()
        selected_answer11_4_2 = self.ans11_4_2.currentText()
        if selected_answer11_4_1 == 'に' and selected_answer11_4_2 =='が':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()
    def check_answer11_5(self):
        selected_answer11_5_1 = self.ans11_5_1.currentText()
        selected_answer11_5_2 = self.ans11_5_2.currentText()
        if selected_answer11_5_1 == 'よく' and selected_answer11_5_2 =='あまり':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()
    def check_answer11_6(self):
        selected_answer11_6 = self.ans11_6.currentText()
        if selected_answer11_6 == 'ときどき':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
