# Form implementation generated from reading ui file 'd:\Python\Bai tap\LapTrinhHDT\Du_an\exercises13.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1931, 982)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1981, 1061))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 991, 1061))
        self.widget_2.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(198, 121, 157, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(60, 200, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(70, 470, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.q2 = QtWidgets.QLabel(parent=self.widget_2)
        self.q2.setGeometry(QtCore.QRect(160, 430, 661, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q2.setFont(font)
        self.q2.setMouseTracking(False)
        self.q2.setTabletTracking(False)
        self.q2.setAcceptDrops(False)
        self.q2.setAutoFillBackground(False)
        self.q2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q2.setScaledContents(False)
        self.q2.setWordWrap(True)
        self.q2.setObjectName("q2")
        self.ans13_2_1 = QtWidgets.QComboBox(parent=self.widget_2)
        self.ans13_2_1.setGeometry(QtCore.QRect(260, 570, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_2_1.setFont(font)
        self.ans13_2_1.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_2_1.setObjectName("ans13_2_1")
        self.ans13_2_1.addItem("")
        self.ans13_2_1.addItem("")
        self.ans13_2_1.addItem("")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(60, 720, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.check13_1 = QtWidgets.QPushButton(parent=self.widget_2)
        self.check13_1.setGeometry(QtCore.QRect(680, 300, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check13_1.setFont(font)
        self.check13_1.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check13_1.setObjectName("check13_1")
        self.check13_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.check13_2.setGeometry(QtCore.QRect(680, 570, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check13_2.setFont(font)
        self.check13_2.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check13_2.setObjectName("check13_2")
        self.q2_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.q2_2.setGeometry(QtCore.QRect(160, 710, 721, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q2_2.setFont(font)
        self.q2_2.setMouseTracking(False)
        self.q2_2.setTabletTracking(False)
        self.q2_2.setAcceptDrops(False)
        self.q2_2.setAutoFillBackground(False)
        self.q2_2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q2_2.setScaledContents(False)
        self.q2_2.setObjectName("q2_2")
        self.check13_3 = QtWidgets.QPushButton(parent=self.widget_2)
        self.check13_3.setGeometry(QtCore.QRect(690, 820, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check13_3.setFont(font)
        self.check13_3.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check13_3.setObjectName("check13_3")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setGeometry(QtCore.QRect(250, 30, 451, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius: 20px;\n"
"border: 2px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.back_gr13 = QtWidgets.QPushButton(parent=self.widget_2)
        self.back_gr13.setGeometry(QtCore.QRect(20, 900, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.back_gr13.setFont(font)
        self.back_gr13.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.back_gr13.setObjectName("back_gr13")
        self.q1_3 = QtWidgets.QLabel(parent=self.widget_2)
        self.q1_3.setGeometry(QtCore.QRect(140, 130, 761, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.q1_3.setFont(font)
        self.q1_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.q1_3.setMouseTracking(True)
        self.q1_3.setTabletTracking(False)
        self.q1_3.setAcceptDrops(False)
        self.q1_3.setAutoFillBackground(False)
        self.q1_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q1_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.q1_3.setScaledContents(False)
        self.q1_3.setWordWrap(True)
        self.q1_3.setIndent(10)
        self.q1_3.setOpenExternalLinks(False)
        self.q1_3.setObjectName("q1_3")
        self.ans13_1_2 = QtWidgets.QComboBox(parent=self.widget_2)
        self.ans13_1_2.setGeometry(QtCore.QRect(380, 300, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_1_2.setFont(font)
        self.ans13_1_2.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_1_2.setObjectName("ans13_1_2")
        self.ans13_1_2.addItem("")
        self.ans13_1_2.addItem("")
        self.ans13_1_2.addItem("")
        self.ans13_1_1 = QtWidgets.QComboBox(parent=self.widget_2)
        self.ans13_1_1.setGeometry(QtCore.QRect(530, 300, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_1_1.setFont(font)
        self.ans13_1_1.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_1_1.setObjectName("ans13_1_1")
        self.ans13_1_1.addItem("")
        self.ans13_1_1.addItem("")
        self.ans13_1_1.addItem("")
        self.ans13_1_3 = QtWidgets.QComboBox(parent=self.widget_2)
        self.ans13_1_3.setGeometry(QtCore.QRect(250, 300, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_1_3.setFont(font)
        self.ans13_1_3.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_1_3.setObjectName("ans13_1_3")
        self.ans13_1_3.addItem("")
        self.ans13_1_3.addItem("")
        self.ans13_1_3.addItem("")
        self.ans13_2_2 = QtWidgets.QComboBox(parent=self.widget_2)
        self.ans13_2_2.setGeometry(QtCore.QRect(400, 570, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_2_2.setFont(font)
        self.ans13_2_2.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_2_2.setObjectName("ans13_2_2")
        self.ans13_2_2.addItem("")
        self.ans13_2_2.addItem("")
        self.ans13_2_2.addItem("")
        self.ans13_2_3 = QtWidgets.QComboBox(parent=self.widget_2)
        self.ans13_2_3.setGeometry(QtCore.QRect(540, 570, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_2_3.setFont(font)
        self.ans13_2_3.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_2_3.setObjectName("ans13_2_3")
        self.ans13_2_3.addItem("")
        self.ans13_2_3.addItem("")
        self.ans13_2_3.addItem("")
        self.ans13_3_1 = QtWidgets.QComboBox(parent=self.widget_2)
        self.ans13_3_1.setGeometry(QtCore.QRect(480, 820, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_3_1.setFont(font)
        self.ans13_3_1.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_3_1.setObjectName("ans13_3_1")
        self.ans13_3_1.addItem("")
        self.ans13_3_1.addItem("")
        self.ans13_3_1.addItem("")
        self.ans13_3_2 = QtWidgets.QComboBox(parent=self.widget_2)
        self.ans13_3_2.setGeometry(QtCore.QRect(270, 820, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_3_2.setFont(font)
        self.ans13_3_2.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_3_2.setObjectName("ans13_3_2")
        self.ans13_3_2.addItem("")
        self.ans13_3_2.addItem("")
        self.ans13_3_2.addItem("")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setGeometry(QtCore.QRect(990, 0, 971, 1061))
        self.widget_3.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(198, 121, 157, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widget_3.setObjectName("widget_3")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(50, 200, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.q1_2 = QtWidgets.QLabel(parent=self.widget_3)
        self.q1_2.setGeometry(QtCore.QRect(150, 180, 711, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.q1_2.setFont(font)
        self.q1_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.q1_2.setMouseTracking(True)
        self.q1_2.setTabletTracking(False)
        self.q1_2.setAcceptDrops(False)
        self.q1_2.setAutoFillBackground(False)
        self.q1_2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q1_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.q1_2.setScaledContents(False)
        self.q1_2.setWordWrap(True)
        self.q1_2.setObjectName("q1_2")
        self.ans13_4_1 = QtWidgets.QComboBox(parent=self.widget_3)
        self.ans13_4_1.setGeometry(QtCore.QRect(440, 310, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_4_1.setFont(font)
        self.ans13_4_1.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_4_1.setObjectName("ans13_4_1")
        self.ans13_4_1.addItem("")
        self.ans13_4_1.addItem("")
        self.ans13_4_1.addItem("")
        self.ans13_4_2 = QtWidgets.QComboBox(parent=self.widget_3)
        self.ans13_4_2.setGeometry(QtCore.QRect(300, 310, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_4_2.setFont(font)
        self.ans13_4_2.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_4_2.setObjectName("ans13_4_2")
        self.ans13_4_2.addItem("")
        self.ans13_4_2.addItem("")
        self.ans13_4_2.addItem("")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(50, 490, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.check13_4 = QtWidgets.QPushButton(parent=self.widget_3)
        self.check13_4.setGeometry(QtCore.QRect(600, 310, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check13_4.setFont(font)
        self.check13_4.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check13_4.setObjectName("check13_4")
        self.check13_5 = QtWidgets.QPushButton(parent=self.widget_3)
        self.check13_5.setGeometry(QtCore.QRect(470, 590, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check13_5.setFont(font)
        self.check13_5.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check13_5.setObjectName("check13_5")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(50, 730, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.q2_3 = QtWidgets.QLabel(parent=self.widget_3)
        self.q2_3.setGeometry(QtCore.QRect(150, 720, 591, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q2_3.setFont(font)
        self.q2_3.setMouseTracking(False)
        self.q2_3.setTabletTracking(False)
        self.q2_3.setAcceptDrops(False)
        self.q2_3.setAutoFillBackground(False)
        self.q2_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q2_3.setScaledContents(False)
        self.q2_3.setWordWrap(True)
        self.q2_3.setObjectName("q2_3")
        self.ans13_6 = QtWidgets.QComboBox(parent=self.widget_3)
        self.ans13_6.setGeometry(QtCore.QRect(270, 830, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_6.setFont(font)
        self.ans13_6.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_6.setObjectName("ans13_6")
        self.ans13_6.addItem("")
        self.ans13_6.addItem("")
        self.ans13_6.addItem("")
        self.check13_6 = QtWidgets.QPushButton(parent=self.widget_3)
        self.check13_6.setGeometry(QtCore.QRect(480, 830, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check13_6.setFont(font)
        self.check13_6.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check13_6.setObjectName("check13_6")
        self.q1 = QtWidgets.QLabel(parent=self.widget_3)
        self.q1.setGeometry(QtCore.QRect(150, 480, 571, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q1.setFont(font)
        self.q1.setMouseTracking(False)
        self.q1.setTabletTracking(False)
        self.q1.setAcceptDrops(False)
        self.q1.setAutoFillBackground(False)
        self.q1.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q1.setScaledContents(False)
        self.q1.setObjectName("q1")
        self.ans13_5 = QtWidgets.QComboBox(parent=self.widget_3)
        self.ans13_5.setGeometry(QtCore.QRect(260, 590, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_5.setFont(font)
        self.ans13_5.setStyleSheet("border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_5.setObjectName("ans13_5")
        self.ans13_5.addItem("")
        self.ans13_5.addItem("")
        self.ans13_5.addItem("")
        self.nextp2_13 = QtWidgets.QPushButton(parent=self.widget_3)
        self.nextp2_13.setGeometry(QtCore.QRect(770, 900, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nextp2_13.setFont(font)
        self.nextp2_13.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.nextp2_13.setObjectName("nextp2_13")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_10.setGeometry(QtCore.QRect(530, 30, 71, 70))
        self.label_10.setMinimumSize(QtCore.QSize(55, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border-radius:35px;\n"
"color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 196, 202);\n"
"border: 2px solid white;\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(410, 30, 71, 70))
        self.label_9.setMinimumSize(QtCore.QSize(55, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border-radius:35px;\n"
"color: rgb(0, 170, 255);\n"
"background-color: rgb(255, 196, 202);\n"
"border: 2px solid white;\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_11.setGeometry(QtCore.QRect(660, 30, 71, 70))
        self.label_11.setMinimumSize(QtCore.QSize(55, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border-radius:35px;\n"
"color: rgb(255, 85, 255);\n"
"background-color: rgb(255, 196, 202);\n"
"border: 2px solid white;\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(280, 30, 71, 70))
        self.label_2.setMinimumSize(QtCore.QSize(55, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius:35px;\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 196, 202);\n"
"border: 2px solid white;\n"
"")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "2"))
        self.q2.setText(_translate("MainWindow", "うち  __(4)__  がっこう　__(5)__　でんしゃ  __(6)__  いきます。"))
        self.ans13_2_1.setItemText(0, _translate("MainWindow", "4?"))
        self.ans13_2_1.setItemText(1, _translate("MainWindow", "から"))
        self.ans13_2_1.setItemText(2, _translate("MainWindow", "まで"))
        self.label_5.setText(_translate("MainWindow", "3"))
        self.check13_1.setText(_translate("MainWindow", "Check"))
        self.check13_2.setText(_translate("MainWindow", "Check"))
        self.q2_2.setText(_translate("MainWindow", "ホテル  __(7)__  タクシー  __(8)__  おります。"))
        self.check13_3.setText(_translate("MainWindow", "Check"))
        self.label.setText(_translate("MainWindow", "Question 1. Choose the correct word:"))
        self.back_gr13.setText(_translate("MainWindow", "Back"))
        self.q1_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.q1_3.setText(_translate("MainWindow", "Ａ：どこ  __(1)__  ちかてつ  __(2)__  のりますか。                                          B: さくらえき __(3)__   のります。"))
        self.ans13_1_2.setItemText(0, _translate("MainWindow", "2?"))
        self.ans13_1_2.setItemText(1, _translate("MainWindow", "に"))
        self.ans13_1_2.setItemText(2, _translate("MainWindow", "で"))
        self.ans13_1_1.setItemText(0, _translate("MainWindow", "3?"))
        self.ans13_1_1.setItemText(1, _translate("MainWindow", "に"))
        self.ans13_1_1.setItemText(2, _translate("MainWindow", "で"))
        self.ans13_1_3.setItemText(0, _translate("MainWindow", "1?"))
        self.ans13_1_3.setItemText(1, _translate("MainWindow", "に"))
        self.ans13_1_3.setItemText(2, _translate("MainWindow", "で"))
        self.ans13_2_2.setItemText(0, _translate("MainWindow", "5?"))
        self.ans13_2_2.setItemText(1, _translate("MainWindow", "から"))
        self.ans13_2_2.setItemText(2, _translate("MainWindow", "まで"))
        self.ans13_2_3.setItemText(0, _translate("MainWindow", "6?"))
        self.ans13_2_3.setItemText(1, _translate("MainWindow", "に"))
        self.ans13_2_3.setItemText(2, _translate("MainWindow", "で"))
        self.ans13_3_1.setItemText(0, _translate("MainWindow", "8?"))
        self.ans13_3_1.setItemText(1, _translate("MainWindow", "に"))
        self.ans13_3_1.setItemText(2, _translate("MainWindow", "で"))
        self.ans13_3_2.setItemText(0, _translate("MainWindow", "7?"))
        self.ans13_3_2.setItemText(1, _translate("MainWindow", "に"))
        self.ans13_3_2.setItemText(2, _translate("MainWindow", "を"))
        self.label_6.setText(_translate("MainWindow", "4"))
        self.q1_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Noto Sans JP\',\'ヒラギノ角ゴ Pro W3\',\'Hiragino Kaku Gothic Pro\',\'メイリオ\',\'Meiryo\',\'ＭＳ Ｐゴシック\',\'sans-serif\'; font-size:20px; color:#717171; background-color:#fffdf7;\">テーブルの うえ           バナナ</span><span style=\" font-family:\'Noto Sans JP\',\'ヒラギノ角ゴ Pro W3\',\'Hiragino Kaku Gothic Pro\',\'メイリオ\',\'Meiryo\',\'ＭＳ Ｐゴシック\',\'sans-serif\'; font-size:20px; font-weight:400; color:#717171; background-color:#fffdf7;\"/><span style=\" font-family:\'Noto Sans JP\',\'ヒラギノ角ゴ Pro W3\',\'Hiragino Kaku Gothic Pro\',\'メイリオ\',\'Meiryo\',\'ＭＳ Ｐゴシック\',\'sans-serif\'; font-size:20px; color:#717171; background-color:#fffdf7;\">あります。</span></p><p><br/><span style=\" font-family:\'Noto Sans JP\'; font-size:18px; color:#717171;\"/><span style=\" font-family:\'Noto Sans JP\'; font-size:18px; font-weight:400; color:#717171;\"/><a name=\"ui-id-4-button\"/><a href=\"https://a1.marugotoweb.jp/en/grammar_topic6_11.php#nogo\"><span style=\" font-family:\'Verdana\',\'Arial\',\'sans-serif\'; font-size:20px; font-weight:400; color:#666666; background-color:#fffdf7; vertical-align:middle;\"><br/></span></a><span style=\" font-family:\'Noto Sans JP\'; font-size:18px; font-weight:400; color:#717171;\"/><a name=\"ui-id-4-button\"/><a href=\"https://a1.marugotoweb.jp/en/grammar_topic6_11.php#nogo\"><span style=\" font-family:\'Verdana\',\'Arial\',\'sans-serif\'; font-size:20px; font-weight:400; color:#666666; background-color:#fffdf7; vertical-align:middle;\"><br/></span></a></p></body></html>"))
        self.q1_2.setText(_translate("MainWindow", "くうこう  __(9)__  バス  __(10)__　いいです。"))
        self.ans13_4_1.setItemText(0, _translate("MainWindow", "10?"))
        self.ans13_4_1.setItemText(1, _translate("MainWindow", "は"))
        self.ans13_4_1.setItemText(2, _translate("MainWindow", "が"))
        self.ans13_4_2.setItemText(0, _translate("MainWindow", "9?"))
        self.ans13_4_2.setItemText(1, _translate("MainWindow", "は"))
        self.ans13_4_2.setItemText(2, _translate("MainWindow", "が"))
        self.label_7.setText(_translate("MainWindow", "5"))
        self.check13_4.setText(_translate("MainWindow", "Check"))
        self.check13_5.setText(_translate("MainWindow", "Check"))
        self.label_8.setText(_translate("MainWindow", "6"))
        self.q2_3.setText(_translate("MainWindow", "がっこうまで　あるいて　___(12)___ 。"))
        self.ans13_6.setItemText(0, _translate("MainWindow", "12?"))
        self.ans13_6.setItemText(1, _translate("MainWindow", "いきます"))
        self.ans13_6.setItemText(2, _translate("MainWindow", "おります"))
        self.check13_6.setText(_translate("MainWindow", "Check"))
        self.q1.setText(_translate("MainWindow", "くうこうで　ひこうきに ___(11)___　。"))
        self.ans13_5.setItemText(0, _translate("MainWindow", "11?"))
        self.ans13_5.setItemText(1, _translate("MainWindow", "のります"))
        self.ans13_5.setItemText(2, _translate("MainWindow", "おります"))
        self.nextp2_13.setText(_translate("MainWindow", "Next"))
        self.label_10.setText(_translate("MainWindow", "が"))
        self.label_9.setText(_translate("MainWindow", "く"))
        self.label_11.setText(_translate("MainWindow", "く"))
        self.label_2.setText(_translate("MainWindow", "ど"))
